version: "3"
services:
  db:
    container_name: pg-local
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: students
    volumes:
      - postgres_data:/var/lib/postgresql/data
  admin:
    container_name: adminer-local
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 9090:8080
volumes: 
  postgres_data:
